package server;

import java.sql.*;
import java.util.ArrayList;
import common.User;
import common.UserRole;

/**
 * Repository class for managing database operations related to users.
 * This class handles authentication, registration, and user identification
 * via various parameters such as ID, username, or QR code.
 */
public class UserRepository {

    private final MySQLConnectionPool pool;

    public UserRepository() {
        this.pool = MySQLConnectionPool.getInstance();
    }

    /**
     * Authenticates a user by their credentials.
     * * @param username The unique username.
     * @param password The user password.
     * @return The User object if found, null otherwise.
     */
    public User login(String username, String password) {
        String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
        PooledConnection pConn = null;
        try {
            pConn = pool.getConnection();
            if (pConn == null) return null;

            Connection conn = pConn.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, password);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                return mapRowToUser(rs);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            if (pConn != null) pool.releaseConnection(pConn);
        }
        return null;
    }

    /**
     * Identifies a user by scanning their unique QR code string.
     * Required for the digital member card identification system.
     * * @param qrCode The unique UUID string stored in the QR code.
     * @return The User object associated with the code, null if not found.
     */
    public User getUserByQRCode(String qrCode) {
        String sql = "SELECT * FROM users WHERE qr_code = ?";
        PooledConnection pConn = null;
        try {
            pConn = pool.getConnection();
            if (pConn == null) return null;

            Connection conn = pConn.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, qrCode);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                return mapRowToUser(rs);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            if (pConn != null) pool.releaseConnection(pConn);
        }
        return null;
    }

    /**
     * Checks if a username already exists in the system.
     * * @param username The username to verify.
     * @return true if the username is taken, false otherwise.
     */
    public boolean isUsernameTaken(String username) {
        String sql = "SELECT COUNT(*) FROM users WHERE username = ?";
        PooledConnection pConn = null;
        try {
            pConn = pool.getConnection();
            if (pConn == null) return true;

            Connection conn = pConn.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, username);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                return rs.getInt(1) > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            if (pConn != null) pool.releaseConnection(pConn);
        }
        return false;
    }

    /**
     * Registers a new user into the database.
     * The primary key (user_id) is automatically generated by the database.
     * * @param u The user object containing registration details.
     * @return The auto-generated user_id (Subscriber ID), or -1 on failure.
     */
    public int registerUser(User u) {
        String sql = "INSERT INTO users (username, password, first_name, last_name, role, phone, email, credit_card, qr_code) " +
                     "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        PooledConnection pConn = null;
        try {
            pConn = pool.getConnection();
            if (pConn == null) return -1;

            Connection conn = pConn.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            
            ps.setString(1, u.getUsername());
            ps.setString(2, u.getPassword());
            ps.setString(3, u.getFirstName());
            ps.setString(4, u.getLastName());
            ps.setString(5, u.getRole().toString());
            ps.setString(6, u.getPhone());
            ps.setString(7, u.getEmail());
            ps.setString(8, u.getCreditCard());
            ps.setString(9, u.getQrCode());

            int affectedRows = ps.executeUpdate();

            if (affectedRows > 0) {
                ResultSet rs = ps.getGeneratedKeys();
                if (rs.next()) {
                    return rs.getInt(1);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            if (pConn != null) pool.releaseConnection(pConn);
        }
        return -1;
    }

    **
    * Updates contact info for an existing user.
    * * @param userId The ID of the user.
    * @param newPhone The updated phone number.
    * @param newEmail The updated email address.
    * @return true if update succeeded.
    */
    public boolean updateUserInfo(int userId, String newPhone, String newEmail) {
        String sql = "UPDATE users SET phone = ?, email = ? WHERE user_id = ?";
        PooledConnection pConn = null;
        try {
            pConn = pool.getConnection();
            if (pConn == null) return false;

            Connection conn = pConn.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, newPhone);
            ps.setString(2, newEmail);
            ps.setInt(3, userId);

            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        } finally {
            if (pConn != null) pool.releaseConnection(pConn);
        }
    }

    /**
     * Maps a ResultSet row to a User object.
     * * @param rs The ResultSet from the database query.
     * @return A User object initialized with the row data.
     * @throws SQLException if data retrieval fails.
     */
    private User mapRowToUser(ResultSet rs) throws SQLException {
        return new User(
            rs.getInt("user_id"),
            rs.getString("username"),
            rs.getString("password"),
            rs.getString("first_name"),
            rs.getString("last_name"),
            UserRole.valueOf(rs.getString("role")),
            rs.getString("phone"),
            rs.getString("email"),
            rs.getString("credit_card"),
            rs.getString("qr_code")
        );
    }
}