package common;

import java.io.Serializable;
import java.sql.Date;

// Represents an order entity implementing Serializable for data transfer.
public class Order implements Serializable {

	// Unique identifier for serialization versioning.
	private static final long serialVersionUID = 1L;

	// DB identifiers
	private int orderNumber; // Unique ID identifying the order.
	private int confirmationCode; // Unique code used for order verification.
	private Date dateOfPlacingOrder; // The timestamp when the order was created.

	// Order details
	private Date orderDate; // The scheduled date for the order.
	private String orderTime;
	private int numberOfGuests; // Total count of guests included in the order.

	// fields for casual customer
	private String customerFirstName;
	private String customerLastName;
	private String customerPhone;
	private String customerEmail;

	private Integer memberID; // ID of the member who placed the order.(Integer for null option (if it is an
									// casual customer)

	// Full Constructor (Server Side / DB Retrieval)
	public Order(int orderNumber, int confirmationCode, Date dateOfPlacingOrder, Date orderDate, String orderTime,
			int numberOfGuests, Integer memberID, String customerFirstName, String customerLastName,String phone, String email) {

		this.orderNumber = orderNumber;
		this.confirmationCode = confirmationCode;
		this.dateOfPlacingOrder = dateOfPlacingOrder;

		this.orderDate = orderDate;
		this.orderTime = orderTime;
		this.numberOfGuests = numberOfGuests;

		this.memberID = memberID;
		this.customerFirstName = customerFirstName;
		
		this.customerPhone = phone;
		this.customerEmail = email;
	}

	// Initializes a new Order instance with all attributes.
	public Order(User user, Date orderDate, String orderTime, int numberOfGuests) {
		// 1. Initialize Default/Pending Values
		this.orderNumber = 0; // Will be assigned by DB (Auto Increment)
		this.confirmationCode = 0; // Will be generated by Server logic
		this.dateOfPlacingOrder = new Date(System.currentTimeMillis()); // Current timestamp

		// 2. Set Order Details from UI
		this.orderDate = orderDate;
		this.orderTime = orderTime;
		this.numberOfGuests = numberOfGuests;


		if (user.getRole() == Role.CASUAL_CUSTOMER) {
			// 3.Casual customers do not have a subscriber ID.
			this.memberID = null;
			// We copy these details to the Order to ensure Casual Customers have contact info saved.
			this.customerFirstName = user.getFirstName();
			this.customerLastName = user.getLastName();
			this.customerPhone = user.getPhone();
			this.customerEmail = user.getEmail();
		} 
		else {
			// Registered Member
			try {
					this.memberID = user.getUserID();
			} 
			catch (NumberFormatException e) {
				// Fallback in case of parsing error
				this.memberID = null;
			}
			
		}
	}

	// Retrieves the order number.
	public int getOrderNumber() {
		return orderNumber;
	}

	// Updates the order number.
	public void setOrderNumber(int orderNumber) {
		this.orderNumber = orderNumber;
	}

	// Retrieves the scheduled order date.
	public Date getOrderDate() {
		return orderDate;
	}

	// Updates the scheduled order date.
	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	// Retrieves the number of guests.
	public int getNumberOfGuests() {
		return numberOfGuests;
	}

	// Updates the number of guests.
	public void setNumberOfGuests(int numberOfGuests) {
		this.numberOfGuests = numberOfGuests;
	}

	// Retrieves the confirmation code.
	public int getConfirmationCode() {
		return confirmationCode;
	}

	// Updates the confirmation code.
	public void setConfirmationCode(int confirmationCode) {
		this.confirmationCode = confirmationCode;
	}

	// Retrieves the subscriber ID.
	public int getMemberID() {
		return memberID;
	}

	// Updates the subscriber ID.
	public void setMemberID(int memberID) {
		this.memberID = memberID;
	}

	// Retrieves the date the order was placed.
	public Date getDateOfPlacingOrder() {
		return dateOfPlacingOrder;
	}

	// Updates the date the order was placed.
	public void setDateOfPlacingOrder(Date dateOfPlacingOrder) {
		this.dateOfPlacingOrder = dateOfPlacingOrder;
	}

	public String getCustomerFirstName() {
		return customerFirstName;
	}

	public void setCustomerFirstName(String customerFirstName) {
		this.customerFirstName = customerFirstName;
	}
	
	public void getCustomerLastName(String customerName) {
		this.customerLastName = customerName;
	}
	
	public void setCustomerLastName(String customerLastName) {
		this.customerLastName = customerLastName;
	}

	public String getCustomerPhone() {
		return customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	public String getCustomerEmail() {
		return customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	// Returns a string representation of the order details.
	@Override
	public String toString() {
		return String.format("Order [Num=%s, Date=%s, Guests=%s, Code=%s, SubID=%s, PlacedOn=%s]", orderNumber,
				orderDate, numberOfGuests, confirmationCode, memberID, dateOfPlacingOrder);
	}
}