package common;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

/**
 * Represents a statistical report generated by the server.
 * <p>
 * This entity is used to transfer aggregated data for:
 * 1. Performance Report (Arrival times, delays).
 * 2. Subscription/Orders Report (Monthly activity).
 * </p>
 */
public class Report implements Serializable {
    
    private static final long serialVersionUID = 1L;

    /** The month the report refers to (1-12). */
    private int month;
    
    /** The year the report refers to. */
    private int year;
    
    /** The type of report (e.g., "PERFORMANCE", "SUBSCRIPTION"). */
    private String reportType; 
    
    /** * The data for the charts.
     * Key: The category name (e.g., "On Time", "Day 1").
     * Value: The numerical value (count/amount).
     */
    private Map<String, Number> dataMap; 

    /**
     * Constructs a new Report.
     * @param month The report month.
     * @param year The report year.
     * @param reportType The type identifier.
     */
    public Report(int month, int year, String reportType) {
        this.month = month;
        this.year = year;
        this.reportType = reportType;
        this.dataMap = new HashMap<>();
    }

    /**
     * Adds a data point to the report map.
     * @param key The label for the chart axis.
     * @param value The value for the chart.
     */
    public void addData(String key, Number value) {
        dataMap.put(key, value);
    }

    public Map<String, Number> getDataMap() { return dataMap; }
    public void setDataMap(Map<String, Number> dataMap) { this.dataMap = dataMap; }

    public int getMonth() { return month; }
    public void setMonth(int month) { this.month = month; }

    public int getYear() { return year; }
    public void setYear(int year) { this.year = year; }

    public String getReportType() { return reportType; }
    public void setReportType(String reportType) { this.reportType = reportType; }
    
    @Override
    public String toString() {
        return reportType + " Report (" + month + "/" + year + ")";
    }
}