package common;

import java.io.Serializable;
import java.util.List;

public class User implements Serializable {

	private static final long serialVersionUID = 1L;

	private Role role;
	private String username;
	private String password;
	private int userID;

	// Member only details
	private String firstName;
	private String lastName;
	private String phone;
	private String email;
	private int memberCode;
	private List<Order> ordersHistory;

	/**
	 * <b>Master Constructor:</b> Used primarily by the Server when fetching existing users from the DB.
	 * <br>Initializes all fields, including technical IDs.
	 *
	 * @param role       The user's role (MEMBER / WORKER / MANAGER).
	 * @param username   Login username (Required).
	 * @param password   Login password (Required).
	 * @param userID     ID (Required).
	 * @param firstName  User's first name.
	 * @param lastName   User's last name.
	 * @param phone      Phone number (Mandatory for MEMBER, optional for others).
	 * @param email      Email address (Mandatory for MEMBER, optional for others).
	 * @param memberCode Unique club member code (Relevant only for MEMBER).
	 */
	public User(Role role, String username, String password, int userID, String firstName, String lastName,
			String phone, String email, int memberCode) {

		this.role = role;
		this.username = username;
		this.password = password;
		this.userID = userID;
		
		this.firstName = firstName;
		this.lastName = lastName;

		if (role == Role.MEMBER) {
            this.phone = phone;
            this.email = email;
            this.memberCode = memberCode;
		}
	}
	/**
	 * <b>Registration Constructor:</b> Used by the Worker when creating a new user.
	 * <br>Automatically sets {@code memberCode} to 0, as it is generated by the Server later.
	 * * @param role       The user's role.
	 * @param username   Login username.
	 * @param password   Login password.
	 * @param firstName  First name.
	 * @param lastName   Last name.
	 * @param phone      Phone number.
	 * @param email      Email address.
	 */
	public User(Role role, String username, String password,int userID, String firstName, String lastName,
			String phone, String email) {
		// Calls the Master Constructor with '0' for memberCode
		this(role, username, password, userID, firstName, lastName, phone, email, 0);
	}
		


	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getUserID() {
		return userID;
	}

	public void setUserID(int userID) {
		this.userID = userID;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public List<Order> getOrdersHistory() {
		return ordersHistory;
	}

	public void setOrdersHistory(List<Order> ordersHistory) {
		this.ordersHistory = ordersHistory;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public int getMemberCode() {
		return memberCode;
	}

	public void setMemberCode(int memberCode) {
		this.memberCode = memberCode;
	}
	
	@Override
	public String toString() {
		return String.format("User [ID=%d, Role=%s, Name=%s %s]", userID, role, firstName, lastName);
	}
}
