package common;

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * Represents a order/reservation in the Bistro system. An Order includes
 * details about the scheduled time, number of guests, contact info, and the
 * current status of the reservation. Important Logic Note: An order reserves a
 * spot based on restaurant capacity, not a specific table ID at the booking
 * stage. The specific table is assigned only upon arrival.
 */
public class Order implements Serializable {

	private static final long serialVersionUID = 1L;

	// Database Identifiers

	private int orderNumber;
	/**
	 * * The code required for the customer to enter the restaurant. Generated by
	 * the server upon approval.
	 */
	private int confirmationCode;

	private int memberId;
	/** The ID of the registered member. 0 if the customer is casual (guest). */

	// Schedule & Timing
	private Timestamp orderDate;
	/** The scheduled date and time for the visit. */
	private Timestamp dateOfPlacingOrder;
	/** The timestamp when this order was actually created/placed in the system. */

	// Order Details
	private int numberOfGuests;
	/**
	 * * The status of the order. Contains: PENDING, APPROVED, NOTIFIED, SEATED,
	 * COMPLETED, CANCELLED,BILLED
	 */
	private String status;
	private double totalPrice;
	/** The final bill amount */
	private Integer assignedTableId;
	/** Physical table ID, null if not currently seated */

	// Contact Info
	private String CustomerName;
	private String phone;
	private String email;

	// For reports
	private Timestamp actualArrivalTime;
	private Timestamp actualLeaveTime;

	public Order() {
	}

	/**
	 * Full Constructor - Used primarily by the Server when retrieving existing data
	 * from the DB.
	 * 
	 * @param orderNumber        Unique order ID from DB.
	 * @param orderDate          Scheduled time for the visit.
	 * @param numberOfGuests     Amount of guests.
	 * @param confirmationCode   Unique code for verification.
	 * @param memberId           The Member ID (or 0 for casual).
	 * @param dateOfPlacingOrder Creation timestamp.
	 */
	public Order(int orderNumber, Timestamp orderDate, int numberOfGuests, int confirmationCode, int memberId,
			Timestamp dateOfPlacingOrder) {
		this.orderNumber = orderNumber;
		this.orderDate = orderDate;
		this.numberOfGuests = numberOfGuests;
		this.confirmationCode = confirmationCode;
		this.memberId = memberId;
		this.dateOfPlacingOrder = dateOfPlacingOrder;
	}

	/**
	 * Client-Side Constructor - Used when a user creates a NEW reservation request.
	 * Initializes the order with 'PENDING' status. The {@code confirmationCode} and
	 * {@code orderNumber} are set to 0, as they will be generated by the server
	 * only after availability check (Best Fit algorithm).
	 *
	 * @param orderDate      Requested time for the visit.
	 * @param numberOfGuests Amount of guests.
	 * @param email          Contact email.
	 * @param phone          Contact phone number.
	 * @param CustomerName   Name of the customer.
	 */
	public Order(Timestamp orderDate, int numberOfGuests, String CustomerName, String phone, String email) {
		this(0, orderDate, numberOfGuests, 0, 0, new Timestamp(System.currentTimeMillis()));

		this.CustomerName = CustomerName;
		this.phone = phone;
		this.email = email;
		this.status = "PENDING"; // Default status for new orders
	}

	// Getters and Setters

	public int getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(int orderNumber) {
		this.orderNumber = orderNumber;
	}

	public int getConfirmationCode() {
		return confirmationCode;
	}

	public void setConfirmationCode(int confirmationCode) {
		this.confirmationCode = confirmationCode;
	}

	public int getMemberId() {
		return memberId;
	}

	public void setMemberId(int MemberId) {
		this.memberId = MemberId;
	}

	public Timestamp getOrderDate() {
		return orderDate;
	}

	public void setOrderDate(Timestamp orderDate) {
		this.orderDate = orderDate;
	}

	public Timestamp getDateOfPlacingOrder() {
		return dateOfPlacingOrder;
	}

	public void setDateOfPlacingOrder(Timestamp dateOfPlacingOrder) {
		this.dateOfPlacingOrder = dateOfPlacingOrder;
	}

	public int getNumberOfGuests() {
		return numberOfGuests;
	}

	public void setNumberOfGuests(int numberOfGuests) {
		this.numberOfGuests = numberOfGuests;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public double getTotalPrice() {
		return totalPrice;
	}

	public void setTotalPrice(double totalPrice) {
		this.totalPrice = totalPrice;
	}

	public Integer getAssignedTableId() {
		return assignedTableId;
	}

	public void setAssignedTableId(Integer assignedTableId) {
		this.assignedTableId = assignedTableId;
	}

	public String getCustomerName() {
		return CustomerName;
	}

	public void setCustomerName(String CustomerName) {
		this.CustomerName = CustomerName;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setActualArrivalTime(Timestamp actualArrivalTime) {
		this.actualArrivalTime = actualArrivalTime;
	}

	public Timestamp getActualLeaveTime() {
		return actualLeaveTime;
	}

	public void setActualLeaveTime(Timestamp actualLeaveTime) {
		this.actualLeaveTime = actualLeaveTime;
	}

	public Timestamp getActualArrivalTime() {
		return actualArrivalTime;
	}

	@Override
	public String toString() {
		return "Order [ID=" + orderNumber + ", Date=" + orderDate + ", Status=" + status + "]";
	}
}