package logic;

import common.User;
import common.Role; 
import server.UserRepository;

/**
 * Service class for managing user-related business logic and restaurant policies.
 * Handles registration, contact updates, and discount calculations (Mission 1 & 5).
 * This version uses integer-based member codes for QR simulation.
 */
public class UserManagement {

    private final UserRepository repo = new UserRepository();

    /**
     * Inner helper class to validate contact information.
     */
    static final class ContactInfo {
        ContactInfo(String phone, String email) {
            if ((phone == null || phone.trim().isEmpty()) && (email == null || email.trim().isEmpty())) {
                throw new IllegalArgumentException("At least one contact method (phone or email) is required.");
            }
        }
    }

    /**
     * Registers a new subscriber with validation and unique member code generation.
     * Required for Mission 1: User Management.
     * @param callerRole The role of the user performing the registration.
     * @param newUser The user data to register.
     * @return The new User ID generated by the database.
     */
    public int registerMember(Role callerRole, User newUser) {
        
        if (callerRole != Role.MANAGER && callerRole != Role.WORKER) {
            throw new IllegalStateException("Only staff can register new members.");
        }
        
        if (newUser.getUsername() == null || newUser.getUsername().trim().isEmpty()) {
            throw new IllegalArgumentException("Username is required.");
        }
        if (repo.isUsernameTaken(newUser.getUsername())) {
            throw new IllegalStateException("Username already exists.");
        }

        new ContactInfo(newUser.getPhone(), newUser.getEmail());

        int generatedMemberCode = (int)(Math.random() * 900000) + 100000; 
        newUser.setMemberCode(generatedMemberCode);

        int newId = repo.registerUser(newUser);
        if (newId == -1) throw new RuntimeException("Database Error during registration.");
        
        return newId;
    }

    /**
     * Calculates final price based on the restaurant's discount policy.
     * Required for Mission 5: Payment Processing.
     * Rule: Members receive a 10% discount on the total bill.
     * @param user The user paying the bill (null if casual).
     * @param originalPrice The base price of the meal.
     * @return Calculated price after eligible discounts.
     */
    public double calculateFinalPrice(User user, double originalPrice) {
        if (user != null && user.getRole() == Role.MEMBER) {
            return originalPrice * 0.9; // 10% Discount applied
        }
        return originalPrice;
    }

    /**
     * Updates the contact information for an existing user.
     * @param userId The unique ID of the user.
     * @param newPhone The new phone number to store.
     * @param newEmail The new email address to store.
     */
    public void updateContact(int userId, String newPhone, String newEmail) {
        new ContactInfo(newPhone, newEmail);
        if (!repo.updateUserInfo(userId, newPhone, newEmail)) {
            throw new RuntimeException("Update failed in database.");
        }
    }
}